# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

---

- name: Enable repository via subscription-manager
  community.general.rhsm_repository:
    name: "{{ mondoo_subscription_manager_repo_id }}"
    state: enabled
  become: "{{ use_become }}"
  when:
    - not ansible_check_mode
    - mondoo_subscription_manager_repo_id is defined
    - mondoo_subscription_manager_repo_id | length > 0

- name: Install Mondoo rpm repository
  ansible.builtin.yum_repository:
    name: mondoo
    description: Mondoo Repository
    baseurl: "{{ mondoo_rpm_repo }}"
    enabled: yes
    gpgcheck: true
    gpgkey: "{{ mondoo_rpm_gpgkey }}"
  become: "{{ use_become }}"
  when:
    - not ansible_check_mode
    - mondoo_subscription_manager_repo_id is undefined or
      mondoo_subscription_manager_repo_id | length = 0

- name: Ensure Mondoo package is installed
  ansible.builtin.yum:
    name: mondoo
    update_cache: yes
    state: latest
  become: "{{ use_become }}"
  when: not ansible_check_mode

- name: Ensure cron is installed
  ansible.builtin.yum:
    name: cronie
    update_cache: yes
    state: latest
  become: "{{ use_become }}"
  when: not ansible_check_mode and update_linux_enabled

- name: Ensuring unmasked crond.service
  ansible.builtin.systemd:
    name: crond.service
    masked: no
  when: update_linux_enabled

- name: Configuring crond.service
  ansible.builtin.service:
    name: crond.service
    state: started
    enabled: yes
  when: update_linux_enabled
