# Copyright Mondoo, Inc. 2026, 0
# SPDX-License-Identifier: BUSL-1.1

---
- name: Converge
  hosts: all
  roles:
    - role: ansible-mondoo
      vars:
        registration_token: ""  # not set by default to test package installation in CI/CD
        use_become: false
