# Copyright Mondoo, Inc. 2026, 0
# SPDX-License-Identifier: BUSL-1.1

---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${image}:${tag:-latest}
    command: ${container_command:-"/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - destroy
